// pages/_app.js
import '../styles/globals.css'

export const metadata = {
  title: 'Barberia',
  description: 'Generated by Next.js',
}

export default function MyApp({ Component, pageProps }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>{metadata.title}</h1>
        </header>
        <main>
          <Component {...pageProps} />
        </main>
        <footer>
          <p>© 2025 Barbería</p>
        </footer>
      </body>
    </html>
  )
}
